### ISSUE TITLE
Mise en collection

### ISSUE THREAD

**Issue by gni** [medaey/role-ansible#1]
## Créer une collection
```bash
ansible-galaxy collection init medaey.devops 
# namespace = medaey 
# collection = devops
# [my_namespace]/[my_collection]/[collection skeleton]
```

## exemple requirements.yaml
```yaml
---
roles:
  # Install via github.
  - name: medaey.devops
    src: git+https://github.com/medaey/devops
    version: 0.0.1
```

## exemple utilisation collection dans un playbook
```yaml
---
- name: example role
  hosts: all
  collections:
    - medaey.devops


  tasks:
    - name: import role docker from devops collection
      import_role:
        name: docker
```
